import type { Lang } from "../types";

export type Triple = Record<Lang, string>;

/** Longest phrases first at runtime. Source-language forms are used for matching. */
export const PHRASES: Triple[] = [
  { en: "thank you for coming tonight", es: "gracias por venir esta noche", pt: "obrigado por vir esta noite" },
  { en: "thank you for coming", es: "gracias por venir", pt: "obrigado por vir" },
  { en: "good to see you", es: "qué bueno verte", pt: "bom te ver" },
  { en: "please be seated", es: "por favor tomen asiento", pt: "por favor sentem-se" },
  { en: "you may be seated", es: "pueden sentarse", pt: "podem sentar-se" },
  { en: "let us begin", es: "comencemos", pt: "vamos começar" },
  { en: "let's get started", es: "empecemos", pt: "vamos começar" },
  { en: "welcome everyone", es: "bienvenidos a todos", pt: "bem-vindos a todos" },
  { en: "see you next week", es: "nos vemos la próxima semana", pt: "vemos você na próxima semana" },
  { en: "see you next time", es: "nos vemos la próxima vez", pt: "até a próxima" },
  { en: "have a good night", es: "que tengan una buena noche", pt: "tenham uma boa noite" },
  { en: "have a good week", es: "que tengan una buena semana", pt: "tenham uma boa semana" },
  { en: "we will close", es: "vamos a cerrar", pt: "vamos encerrar" },
  { en: "one more thing", es: "una cosa más", pt: "mais uma coisa" },
  { en: "can you hear me", es: "¿me escuchan?", pt: "vocês me ouvem?" },
  { en: "let me repeat", es: "permítanme repetir", pt: "deixe-me repetir" },
  { en: "that is all", es: "eso es todo", pt: "isso é tudo" },
  { en: "good morning", es: "buenos días", pt: "bom dia" },
  { en: "good afternoon", es: "buenas tardes", pt: "boa tarde" },
  { en: "good evening", es: "buenas noches", pt: "boa noite" },
  { en: "good night", es: "buenas noches", pt: "boa noite" },
  { en: "next week", es: "la próxima semana", pt: "a próxima semana" },
  { en: "this week", es: "esta semana", pt: "esta semana" },
  { en: "this morning", es: "esta mañana", pt: "esta manhã" },
  { en: "this evening", es: "esta noche", pt: "esta noite" },
  { en: "right now", es: "ahora mismo", pt: "agora mesmo" },
  { en: "thank you", es: "gracias", pt: "obrigado" },
  { en: "you're welcome", es: "de nada", pt: "de nada" },
  { en: "excuse me", es: "perdón", pt: "com licença" },
  { en: "we are going to talk", es: "vamos a hablar", pt: "vamos falar" },
  { en: "let us talk", es: "hablemos", pt: "falemos" },
];

export const WORDS: Triple[] = [
  { en: "welcome", es: "bienvenidos", pt: "bem-vindos" },
  { en: "hello", es: "hola", pt: "olá" },
  { en: "hi", es: "hola", pt: "oi" },
  { en: "friends", es: "amigos", pt: "amigos" },
  { en: "friend", es: "amigo", pt: "amigo" },
  { en: "meeting", es: "reunión", pt: "reunião" },
  { en: "everyone", es: "todos", pt: "todos" },
  { en: "tonight", es: "esta noche", pt: "esta noite" },
  { en: "today", es: "hoy", pt: "hoje" },
  { en: "tomorrow", es: "mañana", pt: "amanhã" },
  { en: "yesterday", es: "ayer", pt: "ontem" },
  { en: "please", es: "por favor", pt: "por favor" },
  { en: "thanks", es: "gracias", pt: "obrigado" },
  { en: "yes", es: "sí", pt: "sim" },
  { en: "no", es: "no", pt: "não" },
  { en: "love", es: "amor", pt: "amor" },
  { en: "peace", es: "paz", pt: "paz" },
  { en: "word", es: "palabra", pt: "palavra" },
  { en: "begin", es: "comenzar", pt: "começar" },
  { en: "start", es: "empezar", pt: "começar" },
  { en: "started", es: "empezó", pt: "começou" },
  { en: "close", es: "cerrar", pt: "encerrar" },
  { en: "end", es: "fin", pt: "fim" },
  { en: "listen", es: "escuchar", pt: "ouvir" },
  { en: "hear", es: "oír", pt: "ouvir" },
  { en: "speak", es: "hablar", pt: "falar" },
  { en: "say", es: "decir", pt: "dizer" },
  { en: "said", es: "dijo", pt: "disse" },
  { en: "look", es: "miren", pt: "olhem" },
  { en: "come", es: "vengan", pt: "venham" },
  { en: "coming", es: "viniendo", pt: "vindo" },
  { en: "go", es: "vayan", pt: "vão" },
  { en: "stand", es: "pónganse de pie", pt: "fiquem de pé" },
  { en: "sit", es: "siéntense", pt: "sentem-se" },
  { en: "seated", es: "sentados", pt: "sentados" },
  { en: "together", es: "juntos", pt: "juntos" },
  { en: "again", es: "otra vez", pt: "de novo" },
  { en: "now", es: "ahora", pt: "agora" },
  { en: "then", es: "entonces", pt: "então" },
  { en: "here", es: "aquí", pt: "aqui" },
  { en: "there", es: "allí", pt: "ali" },
  { en: "this", es: "esto", pt: "isto" },
  { en: "that", es: "eso", pt: "isso" },
  { en: "these", es: "estos", pt: "estes" },
  { en: "those", es: "esos", pt: "esses" },
  { en: "we", es: "nosotros", pt: "nós" },
  { en: "you", es: "ustedes", pt: "vocês" },
  { en: "they", es: "ellos", pt: "eles" },
  { en: "i", es: "yo", pt: "eu" },
  { en: "our", es: "nuestro", pt: "nosso" },
  { en: "your", es: "su", pt: "seu" },
  { en: "my", es: "mi", pt: "meu" },
  { en: "and", es: "y", pt: "e" },
  { en: "or", es: "o", pt: "ou" },
  { en: "but", es: "pero", pt: "mas" },
  { en: "because", es: "porque", pt: "porque" },
  { en: "if", es: "si", pt: "se" },
  { en: "so", es: "entonces", pt: "então" },
  { en: "for", es: "para", pt: "para" },
  { en: "with", es: "con", pt: "com" },
  { en: "without", es: "sin", pt: "sem" },
  { en: "from", es: "de", pt: "de" },
  { en: "to", es: "a", pt: "para" },
  { en: "in", es: "en", pt: "em" },
  { en: "on", es: "en", pt: "em" },
  { en: "of", es: "de", pt: "de" },
  { en: "the", es: "el", pt: "o" },
  { en: "a", es: "un", pt: "um" },
  { en: "an", es: "un", pt: "um" },
  { en: "is", es: "es", pt: "é" },
  { en: "are", es: "son", pt: "são" },
  { en: "was", es: "fue", pt: "foi" },
  { en: "were", es: "fueron", pt: "foram" },
  { en: "be", es: "ser", pt: "ser" },
  { en: "been", es: "sido", pt: "sido" },
  { en: "will", es: "va a", pt: "vai" },
  { en: "can", es: "puede", pt: "pode" },
  { en: "let", es: "dejemos", pt: "vamos" },
  { en: "lets", es: "vamos", pt: "vamos" },
  { en: "let's", es: "vamos", pt: "vamos" },
  { en: "us", es: "nosotros", pt: "nós" },
  { en: "not", es: "no", pt: "não" },
  { en: "very", es: "muy", pt: "muito" },
  { en: "more", es: "más", pt: "mais" },
  { en: "all", es: "todos", pt: "todos" },
  { en: "everyone", es: "todos", pt: "todos" },
  { en: "someone", es: "alguien", pt: "alguém" },
  { en: "anyone", es: "cualquiera", pt: "qualquer um" },
  { en: "good", es: "bueno", pt: "bom" },
  { en: "great", es: "grande", pt: "ótimo" },
  { en: "true", es: "verdadero", pt: "verdadeiro" },
  { en: "first", es: "primero", pt: "primeiro" },
  { en: "second", es: "segundo", pt: "segundo" },
  { en: "last", es: "último", pt: "último" },
  { en: "next", es: "siguiente", pt: "próximo" },
  { en: "week", es: "semana", pt: "semana" },
  { en: "night", es: "noche", pt: "noite" },
  { en: "morning", es: "mañana", pt: "manhã" },
  { en: "evening", es: "noche", pt: "noite" },
  { en: "time", es: "tiempo", pt: "tempo" },
  { en: "house", es: "casa", pt: "casa" },
  { en: "home", es: "hogar", pt: "lar" },
  { en: "family", es: "familia", pt: "família" },
  { en: "son", es: "hijo", pt: "filho" },
  { en: "father", es: "padre", pt: "pai" },
  { en: "heart", es: "corazón", pt: "coração" },
  { en: "life", es: "vida", pt: "vida" },
  { en: "truth", es: "verdad", pt: "verdade" },
  { en: "name", es: "nombre", pt: "nome" },
  { en: "please", es: "por favor", pt: "por favor" },
  { en: "open", es: "abran", pt: "abram" },
  { en: "read", es: "lean", pt: "leiam" },
  { en: "repeat", es: "repitan", pt: "repitam" },
  { en: "follow", es: "sigan", pt: "sigam" },
  { en: "wait", es: "esperen", pt: "esperem" },
  { en: "one", es: "uno", pt: "um" },
  { en: "two", es: "dos", pt: "dois" },
  { en: "three", es: "tres", pt: "três" },
  { en: "four", es: "cuatro", pt: "quatro" },
  { en: "five", es: "cinco", pt: "cinco" },
  { en: "six", es: "seis", pt: "seis" },
  { en: "seven", es: "siete", pt: "sete" },
  { en: "eight", es: "ocho", pt: "oito" },
  { en: "nine", es: "nueve", pt: "nove" },
  { en: "ten", es: "diez", pt: "dez" },
  { en: "the", es: "la", pt: "a" },
  { en: "the", es: "los", pt: "os" },
  { en: "the", es: "las", pt: "as" },
  { en: "a", es: "una", pt: "uma" },
  { en: "about", es: "sobre", pt: "sobre" },
  { en: "of the", es: "del", pt: "do" },
  { en: "to the", es: "al", pt: "ao" },
  { en: "this", es: "esta", pt: "esta" },
  { en: "this", es: "este", pt: "este" },
  { en: "what", es: "qué", pt: "quê" },
  { en: "that", es: "que", pt: "que" },
  { en: "talk", es: "hablar", pt: "falar" },
  { en: "is", es: "está", pt: "está" },
  { en: "are", es: "están", pt: "estão" },
  { en: "I am", es: "estoy", pt: "estou" },
  { en: "we are", es: "estamos", pt: "estamos" },
  { en: "there is", es: "hay", pt: "há" },
  { en: "has", es: "tiene", pt: "tem" },
  { en: "have", es: "tienen", pt: "têm" },
  { en: "also", es: "también", pt: "também" },
  { en: "how", es: "como", pt: "como" },
  { en: "when", es: "cuando", pt: "quando" },
  { en: "where", es: "donde", pt: "onde" },
  { en: "who", es: "quién", pt: "quem" },
  { en: "her", es: "le", pt: "lhe" },
  { en: "them", es: "les", pt: "lhes" },
  { en: "me", es: "me", pt: "me" },
  { en: "us", es: "nos", pt: "nos" },
];
